create table if not exists public.marketplace_admin_credentials (
  credential_name text primary key,
  pin_hash text not null,
  is_active boolean not null default true,
  updated_at timestamptz not null default now()
);

alter table public.marketplace_admin_credentials enable row level security;
revoke all on table public.marketplace_admin_credentials from anon, authenticated;

create table if not exists public.marketplace_admin_login_attempts (
  id bigint generated by default as identity primary key,
  ip_hash text not null,
  attempted_at timestamptz not null default now(),
  succeeded boolean not null default false
);

create index if not exists marketplace_admin_login_attempts_ip_time_idx
  on public.marketplace_admin_login_attempts (ip_hash, attempted_at desc);

alter table public.marketplace_admin_login_attempts enable row level security;
revoke all on table public.marketplace_admin_login_attempts from anon, authenticated;

create or replace function public.verify_marketplace_admin_pin(p_pin text)
returns boolean
language sql
security definer
set search_path = public, extensions
as $$
  select exists (
    select 1
    from public.marketplace_admin_credentials
    where credential_name = 'primary'
      and is_active = true
      and pin_hash = extensions.crypt(p_pin, pin_hash)
  );
$$;

revoke all on function public.verify_marketplace_admin_pin(text) from public, anon, authenticated;
grant execute on function public.verify_marketplace_admin_pin(text) to service_role;
